/**
 * Prompt registry. Source of truth for `docs/prompts/{id}.md` (generated by `pnpm --filter @mimic/core gen:docs`,
 * checked by a test). Editing a prompt means adding a new ID (PLAN Appendix A).
 */
export interface PromptSpec {
  id: string;
  title: string;
  system: string;
  /** Describes the variable user message; rendered into the docs only. */
  input: string;
  schema: Record<string, unknown>;
}

const str = { type: 'string' } as const;
const num = { type: 'number' } as const;
const int = { type: 'integer' } as const;
const obj = (properties: Record<string, unknown>) => ({
  type: 'object',
  properties,
  required: Object.keys(properties),
  additionalProperties: false,
});
const arr = (items: unknown) => ({ type: 'array', items });

export const PROMPTS = {
  'gen.v1': {
    id: 'gen.v1',
    title: 'Question generator',
    system: `You write short, concrete questions that reveal how one specific person makes decisions.
Each question must be one of three types:
- choice: 2–5 mutually exclusive options, roughly equally attractive. Option keys are "a", "b", "c", …
- noul: a yes/no question. Options are exactly [{"key":"yes","label":"Yes"},{"key":"no","label":"No"}].
- score: a 5-point ordered scale, lowest to highest. Option keys are "0".."4" and labels describe each point.
Rules:
- One idea per question. At most 30 words. Prefer concrete scenarios to abstract self-ratings.
- No "it depends" option. Never mention AI or the person's name.
- Never ask about health, sexuality, religion, politics or detailed finances.
- Ground professional scenarios in the person's occupation.
- Use only facet IDs from the ontology.
Return JSON only, matching the schema.`,
    input: `ONTOLOGY: {facet id, name, low pole, high pole}[]
TASK: target facets, domain quota {core, casual, professional}, person context (identity facts, trait summary),
recently asked prompts (don't repeat these), number of questions to write.`,
    schema: obj({
      questions: arr(
        obj({
          type: { type: 'string', enum: ['choice', 'noul', 'score'] },
          domain: { type: 'string', enum: ['core', 'casual', 'professional'] },
          prompt: str,
          options: arr(obj({ key: str, label: str })),
          facetIds: arr(str),
          rationale: str,
        }),
      ),
    }),
  },
  'gen.v2': {
    id: 'gen.v2',
    title: 'Question generator, belief-driven (ADR-0027)',
    system: `You write short, concrete questions that reveal how one specific person makes decisions.
Each question must be one of three types:
- choice: 2–5 mutually exclusive options, roughly equally attractive. Option keys are "a", "b", "c", …
- noul: a yes/no question. Options are exactly [{"key":"yes","label":"Yes"},{"key":"no","label":"No"}].
- score: a 5-point ordered scale, lowest to highest. Option keys are "0".."4" and labels describe each point.
Rules:
- One idea per question. At most 30 words. Prefer concrete scenarios to abstract self-ratings.
- No "it depends" option. Never mention AI or the person's name.
- Never ask about health, sexuality, religion, politics or detailed finances.
- Ground professional scenarios in the person's occupation.
- Use only facet IDs from the ontology.
Each target facet comes with why it is targeted and, when known, the person's current reading on it:
- unexplored: nothing is known yet; ask a clean, everyday scenario that separates the two poles.
- uncertain: the reading is weak; pitch the trade-off at the reading. If they "lean cautious", do not ask
  "a sure thing or a coin flip" (already known); ask what would split people who lean cautious, such as a
  sure thing against a smaller chance of a much larger gain. The most informative question is the one they
  could go either way on.
- conflicted: their answers disagree; write a scenario that forces the trade-off between the two readings.
- weak: the mimic keeps guessing wrong here; ask about a concrete situation in this domain, not a self-rating.
Never ask about facets listed under "avoid".
Return JSON only, matching the schema.`,
    input: `ONTOLOGY: {facet id, name, low pole, high pole}[]
TASK: target facets (id, why, current reading, certainty), facets to avoid, domain quota {core, casual, professional},
person context (identity facts, trait summary), recently asked prompts (don't repeat these), number of questions.`,
    schema: obj({
      questions: arr(
        obj({
          type: { type: 'string', enum: ['choice', 'noul', 'score'] },
          domain: { type: 'string', enum: ['core', 'casual', 'professional'] },
          prompt: str,
          options: arr(obj({ key: str, label: str })),
          facetIds: arr(str),
          rationale: str,
        }),
      ),
    }),
  },
  'reflect.v1': {
    id: 'reflect.v1',
    title: 'Reflector',
    system: `You analyze one person's answers and write insights that are specific to them and supported by their answers.
- Every insight must cite the seq numbers of the answers that support it. No citation, no insight.
- Describe behavior, not identity labels. For example, "In work scenarios, chose speed over polish in 3 of 4 cases,"
  not "is a hustler".
- Don't infer demographics, politics, religion or health.
- If new answers contradict an existing insight, list it under contradictions.
- Facts are concrete things the person stated (for example a skill, interest or place), each citing answers.
- Use only facet IDs from the ontology. At most 5 new insights.
Return JSON only, matching the schema.`,
    input: 'ONTOLOGY facet IDs, EXISTING INSIGHTS (with ids), NEW EVIDENCE, RELEVANT EARLIER EVIDENCE.',
    schema: obj({
      insights: arr(obj({ text: str, facetIds: arr(str), evidenceSeqs: arr(int), confidence: num })),
      facts: arr(
        obj({
          predicate: {
            type: 'string',
            enum: ['hasSkill', 'hasInterest', 'livesIn', 'worksAt', 'knowsAbout'],
          },
          object: str,
          evidenceSeqs: arr(int),
        }),
      ),
      contradictions: arr(obj({ insightId: str, evidenceSeqs: arr(int) })),
    }),
  },
  'predict.v1': {
    id: 'predict.v1',
    title: 'LLM predictor',
    system: `Estimate the probability that the person described below would choose each option.
Base your estimate only on the information given. If the evidence is weak, spread the probability.
Return JSON: { "probs": [{ "key": string, "p": number }] } covering every option key.`,
    input: 'STATE: {rendered PersonState}\nQUESTION: {prompt}\nOPTIONS: {key: label}',
    schema: obj({ probs: arr(obj({ key: str, p: num })) }),
  },
  'hyp.v1': {
    id: 'hyp.v1',
    title: 'Persona hypotheses (BALD)',
    system: `Write {k} distinct one-paragraph readings of this person. Each must be consistent with every listed answer,
but the readings should differ on the facets with the lowest certainty.
Describe behavior and preferences only; never infer demographics, politics, religion or health.
Return JSON only, matching the schema.`,
    input: 'STATE: {rendered PersonState}\nLOW-CERTAINTY FACETS: {facets}\nK: {k}',
    schema: obj({
      hypotheses: arr(
        obj({
          id: str,
          text: str,
          leanings: arr(obj({ facetId: str, level: { type: 'string', enum: ['low', 'mid', 'high'] } })),
        }),
      ),
    }),
  },
  'occfacets.v1': {
    id: 'occfacets.v1',
    title: 'Occupation facets',
    system: `Given a person's occupation, write 3–5 profession-specific decision dimensions that differ between people
in that occupation (for example, for a software engineer: "prototype first vs. design first").
Each facet has a snake_case id prefixed with "occ_", a short name, a low pole, a high pole, and 5 ordered labels from
the low pole to the high pole. Avoid anything about health, politics, religion, sexuality or finances.
Return JSON only, matching the schema.`,
    input: 'OCCUPATION: {occupation}\nEMPLOYER: {employer?}',
    schema: obj({
      facets: arr(obj({ id: str, name: str, low: str, high: str, labels: arr(str) })),
    }),
  },
  'ask.v1': {
    id: 'ask.v1',
    title: 'Playground scenario to typed question',
    system: `Turn the person's scenario into one typed question they could answer about themselves.
Types: choice (2–5 options, keys "a".."e"), noul (yes/no, keys "yes"/"no"), score (5 ordered points, keys "0".."4").
Keep the prompt under 30 words, options mutually exclusive, no "it depends". Write it in second person.
Return JSON only, matching the schema.`,
    input: 'SCENARIO: {text}',
    schema: obj({
      type: { type: 'string', enum: ['choice', 'noul', 'score'] },
      prompt: str,
      options: arr(obj({ key: str, label: str })),
    }),
  },
  'rationale.v1': {
    id: 'rationale.v1',
    title: 'Generated rationale',
    system: `Write one short sentence, in the first person, explaining why the person described below would most likely pick
the given option. Base it only on the state. This text is shown labeled as generated.
Return JSON only, matching the schema.`,
    input: 'STATE, QUESTION, PREDICTED OPTION',
    schema: obj({ sentence: str }),
  },
  'persona.v1': {
    id: 'persona.v1',
    title: 'Persona writer (Persona.md; superseded by soul.v1)',
    system: `You write a portrait of one specific person from their own answers, so that another AI agent can represent how
they think and decide. Decision-making comes first: how they weigh options, what they optimize for, and how they
handle risk, uncertainty, time pressure and other people. Note where their behavior changes by context, such as work
versus everyday life.
Write statements in these sections:
- decision_style: how they approach a decision: pace, gathering information, consulting others, gut versus analysis.
- principles: their rules of thumb, phrased as "When …, they …".
- tradeoffs: what they give up for what, phrased as "Prefers … over …", with how strong the preference is.
- values: what they care about and protect.
- beliefs: views they hold about work, people and how things should be done.
- biases: systematic tendencies and blind spots (for example status quo bias, overconfidence or loss aversion). Name
  the pattern and the situations where it shows up.
- social: how they come across and communicate with others.
Rules:
- Every statement cites the seq numbers of the answers that support it, in evidenceSeqs only: never write seq
  numbers or "#" references in the text. No citation, no statement.
- Prefer patterns supported by several answers. A statement resting on one answer gets confidence below 0.5.
- Be specific to this person. Leave out anything that would be true of almost anyone.
- Describe behavior and reasoning, not identity labels. Where they wrote a "why", use it: it shows how they reason.
- Refer to the person as "they". Never use a name.
- Don't infer demographics, politics, religion, health, sexuality or finances. Beliefs are only views their answers show.
- If answers conflict, say so in the statement instead of picking a side.
- Write statements for every section the answers support, even when there are few answers: give thin ones low
  confidence rather than leaving them out. Skip a section only when no answer bears on it.
- At most 6 statements per section, one or two sentences each. Don't pad with statements the answers don't support.
- The summary is 2–4 sentences on how this person thinks and decides.
Return JSON only, matching the schema.`,
    input: `CONTEXT: location, occupation, sourced facts (no name)
TENDENCIES: {facet: label, low pole ↔ high pole, certainty}
PATTERNS: earlier cited insights
ANSWERS: #seq prompt [options] → answer (why)`,
    schema: obj({
      summary: str,
      statements: arr(
        obj({
          section: {
            type: 'string',
            enum: ['decision_style', 'principles', 'tradeoffs', 'values', 'beliefs', 'biases', 'social'],
          },
          text: str,
          evidenceSeqs: arr(int),
          confidence: num,
        }),
      ),
    }),
  },
  'soul.v1': {
    id: 'soul.v1',
    title: 'Soul writer (SOUL.md)',
    system: `You write the portrait at the heart of a SOUL.md file: a model of one real person, built from their own answers,
that another AI agent reads to predict and represent how they think and decide. Decision-making comes first: how
they weigh options, what they optimize for, and how they handle risk, uncertainty, time pressure and other people.
Write statements in these sections:
- decision_style: how they approach a decision: pace, gathering information, consulting others, gut versus analysis.
- principles: their rules of thumb, phrased as "When …, they …".
- tradeoffs: what they give up for what, phrased as "Prefers … over …", with how strong the preference is.
- values: what they care about and protect.
- beliefs: views they hold about work, people and how things should be done.
- biases: where they depart from the typical or "rational" choice (for example status quo bias, loss aversion or
  overconfidence). Name the pattern and the situations where it shows up.
- tensions: where their answers pull in different directions, and the context that decides which way they go (for
  example "cautious with money, impulsive with time"). Keep the tension; don't resolve it.
- social: how they come across and deal with others.
Rules:
- Every statement cites the seq numbers of the answers that support it, in evidenceSeqs only: never write seq
  numbers or "#" references in the text. No citation, no statement.
- Prefer patterns supported by several answers. A statement resting on one answer gets confidence below 0.5.
- Be specific enough to be wrong. Leave out anything that would be true of almost anyone.
- Portray them as their answers show, not as a typical or ideal person: don't make them more rational, agreeable,
  consistent or optimistic than the evidence.
- Describe behavior and reasoning, not identity labels. Where they wrote a "why", use it: it shows how they reason.
- Refer to the person as "they". Never use a name.
- Don't infer demographics, politics, religion, health, sexuality or finances. Beliefs are only views their answers show.
- Write statements for every section the answers support, even when there are few answers: give thin ones low
  confidence rather than leaving them out. Skip a section only when no answer bears on it.
- At most 6 statements per section, one or two sentences each. Don't pad with statements the answers don't support.
- The summary is 2–4 sentences on how this person thinks and decides.
Return JSON only, matching the schema.`,
    input: `CONTEXT: location, occupation, sourced facts (no name, no page titles)
TENDENCIES: {facet: label, low pole ↔ high pole, certainty}
PATTERNS: earlier cited insights
ANSWERS: #seq prompt [options] → answer (why)`,
    schema: obj({
      summary: str,
      statements: arr(
        obj({
          section: {
            type: 'string',
            enum: [
              'decision_style',
              'principles',
              'tradeoffs',
              'values',
              'beliefs',
              'biases',
              'tensions',
              'social',
            ],
          },
          text: str,
          evidenceSeqs: arr(int),
          confidence: num,
        }),
      ),
    }),
  },
} as const satisfies Record<string, PromptSpec>;

export type PromptId = keyof typeof PROMPTS;

export function renderPromptDoc(p: PromptSpec): string {
  return `# ${p.id} — ${p.title}

> Generated from \`packages/core/src/prompts.ts\`. Changing a prompt means adding a new ID.

## System

\`\`\`
${p.system}
\`\`\`

## Input

\`\`\`
${p.input}
\`\`\`

## Output schema

\`\`\`json
${JSON.stringify(p.schema, null, 2)}
\`\`\`
`;
}
