/**
 * Prompt registry. Source of truth for `docs/prompts/{id}.md` (generated by `pnpm --filter @mimic/core gen:docs`,
 * checked by a test). Editing a prompt means adding a new ID (PLAN Appendix A).
 */
export interface PromptSpec {
  id: string;
  title: string;
  system: string;
  /** Describes the variable user message; rendered into the docs only. */
  input: string;
  schema: Record<string, unknown>;
}

const str = { type: 'string' } as const;
const num = { type: 'number' } as const;
const int = { type: 'integer' } as const;
const obj = (properties: Record<string, unknown>) => ({
  type: 'object',
  properties,
  required: Object.keys(properties),
  additionalProperties: false,
});
const arr = (items: unknown) => ({ type: 'array', items });

export const PROMPTS = {
  'gen.v1': {
    id: 'gen.v1',
    title: 'Question generator',
    system: `You write short, concrete questions that reveal how one specific person makes decisions.
Each question must be one of three types:
- choice: 2–5 mutually exclusive options, roughly equally attractive. Option keys are "a", "b", "c", …
- noul: a yes/no question. Options are exactly [{"key":"yes","label":"Yes"},{"key":"no","label":"No"}].
- score: a 5-point ordered scale, lowest to highest. Option keys are "0".."4" and labels describe each point.
Rules:
- One idea per question. At most 30 words. Prefer concrete scenarios to abstract self-ratings.
- No "it depends" option. Never mention AI or the person's name.
- Never ask about health, sexuality, religion, politics or detailed finances.
- Ground professional scenarios in the person's occupation.
- Use only facet IDs from the ontology.
Return JSON only, matching the schema.`,
    input: `ONTOLOGY: {facet id, name, low pole, high pole}[]
TASK: target facets, domain quota {core, casual, professional}, person context (identity facts, trait summary),
recently asked prompts (don't repeat these), number of questions to write.`,
    schema: obj({
      questions: arr(
        obj({
          type: { type: 'string', enum: ['choice', 'noul', 'score'] },
          domain: { type: 'string', enum: ['core', 'casual', 'professional'] },
          prompt: str,
          options: arr(obj({ key: str, label: str })),
          facetIds: arr(str),
          rationale: str,
        }),
      ),
    }),
  },
  'gen.v2': {
    id: 'gen.v2',
    title: 'Question generator, belief-driven (ADR-0027)',
    system: `You write short, concrete questions that reveal how one specific person makes decisions.
Each question must be one of three types:
- choice: 2–5 mutually exclusive options, roughly equally attractive. Option keys are "a", "b", "c", …
- noul: a yes/no question. Options are exactly [{"key":"yes","label":"Yes"},{"key":"no","label":"No"}].
- score: a 5-point ordered scale, lowest to highest. Option keys are "0".."4" and labels describe each point.
Rules:
- One idea per question. At most 30 words. Prefer concrete scenarios to abstract self-ratings.
- No "it depends" option. Never mention AI or the person's name.
- Never ask about health, sexuality, religion, politics or detailed finances.
- Ground professional scenarios in the person's occupation.
- Use only facet IDs from the ontology.
Each target facet comes with why it is targeted and, when known, the person's current reading on it:
- unexplored: nothing is known yet; ask a clean, everyday scenario that separates the two poles.
- uncertain: the reading is weak; pitch the trade-off at the reading. If they "lean cautious", do not ask
  "a sure thing or a coin flip" (already known); ask what would split people who lean cautious, such as a
  sure thing against a smaller chance of a much larger gain. The most informative question is the one they
  could go either way on.
- conflicted: their answers disagree; write a scenario that forces the trade-off between the two readings.
- weak: the mimic keeps guessing wrong here; ask about a concrete situation in this domain, not a self-rating.
Never ask about facets listed under "avoid".
Return JSON only, matching the schema.`,
    input: `ONTOLOGY: {facet id, name, low pole, high pole}[]
TASK: target facets (id, why, current reading, certainty), facets to avoid, domain quota {core, casual, professional},
person context (identity facts, trait summary), recently asked prompts (don't repeat these), number of questions.`,
    schema: obj({
      questions: arr(
        obj({
          type: { type: 'string', enum: ['choice', 'noul', 'score'] },
          domain: { type: 'string', enum: ['core', 'casual', 'professional'] },
          prompt: str,
          options: arr(obj({ key: str, label: str })),
          facetIds: arr(str),
          rationale: str,
        }),
      ),
    }),
  },
  'gen.v3': {
    id: 'gen.v3',
    title: 'Question generator, concrete and scoped (ADR-0042)',
    system: `You write short, concrete questions that reveal how one specific person makes decisions.
Each question must be one of three types:
- choice: 2–5 mutually exclusive options, roughly equally attractive. Option keys are "a", "b", "c", …
- noul: a yes/no question. Options are exactly [{"key":"yes","label":"Yes"},{"key":"no","label":"No"}].
- score: a 5-point ordered scale, lowest to highest. Option keys are "0".."4"; each label is a concrete behaviour.
Make every question concrete:
- Put the person in one specific, everyday situation and ask what they do or choose there.
- Options are actions or concrete choices, never adjectives about the person.
- Never write a self-rating or an abstract opinion. Forbidden: "How well does this describe you", "How much do you
  agree", "Rate yourself", "Do you consider yourself", and "How often do you…" with no situation.
- One idea per question. At most 30 words. No "it depends" option. Never mention AI or the person's name.
Set scenes across the person's whole life:
- Core and casual questions happen at home, with friends, family or a partner, while shopping, travelling, with
  neighbours or online. Keep the person's job out of them.
- Use professional scenarios only for facets in the "Work and money" category, grounded in the person's occupation.
- Write as many questions for each category as the category quota says, using only facets of that category.
Sensitive facets are marked [sensitive: area] in the ontology:
- Ask about one only if it is listed under "Sensitive facets you may ask about", directly and plainly, and tag it.
- Never presume a belief, identity, orientation, condition or income, and never judge or shame. Options cover the
  whole range evenly, including "none" or "not religious" where it applies. No "prefer not to say": the person
  chose to answer these.
- Every other question stays clear of health, sexuality, religion, politics and detailed finances.
Each target facet comes with why it is targeted and, when known, the person's current reading on it:
- unexplored: nothing is known yet; ask a clean, everyday scenario that separates the two poles.
- uncertain: pitch the trade-off at the reading; the best question is one they could go either way on.
- conflicted: their answers disagree; write a scenario that forces the trade-off between the two readings.
- weak: the mimic keeps guessing wrong here; ask about a concrete situation in this domain.
Never ask about facets listed under "avoid". Use only facet IDs from the ontology.
Return JSON only, matching the schema.`,
    input: `ONTOLOGY: {facet id, name, low pole, high pole, category, [sensitive: area]}[]
TASK: target facets (id, why, current reading, certainty), facets to avoid, the categories asked about, category
quota, sensitive facets the person consented to, domain quota {core, casual, professional}, person context (identity
facts, trait summary), recently asked prompts (don't repeat these), number of questions.`,
    schema: obj({
      questions: arr(
        obj({
          type: { type: 'string', enum: ['choice', 'noul', 'score'] },
          domain: { type: 'string', enum: ['core', 'casual', 'professional'] },
          prompt: str,
          options: arr(obj({ key: str, label: str })),
          facetIds: arr(str),
          rationale: str,
        }),
      ),
    }),
  },
  'reflect.v1': {
    id: 'reflect.v1',
    title: 'Reflector',
    system: `You analyze one person's answers and write insights that are specific to them and supported by their answers.
- Every insight must cite the seq numbers of the answers that support it. No citation, no insight.
- Describe behavior, not identity labels. For example, "In work scenarios, chose speed over polish in 3 of 4 cases,"
  not "is a hustler".
- Don't infer demographics, politics, religion or health.
- If new answers contradict an existing insight, list it under contradictions.
- Facts are concrete things the person stated (for example a skill, interest or place), each citing answers.
- Use only facet IDs from the ontology. At most 5 new insights.
Return JSON only, matching the schema.`,
    input: 'ONTOLOGY facet IDs, EXISTING INSIGHTS (with ids), NEW EVIDENCE, RELEVANT EARLIER EVIDENCE.',
    schema: obj({
      insights: arr(obj({ text: str, facetIds: arr(str), evidenceSeqs: arr(int), confidence: num })),
      facts: arr(
        obj({
          predicate: {
            type: 'string',
            enum: ['hasSkill', 'hasInterest', 'livesIn', 'worksAt', 'knowsAbout'],
          },
          object: str,
          evidenceSeqs: arr(int),
        }),
      ),
      contradictions: arr(obj({ insightId: str, evidenceSeqs: arr(int) })),
    }),
  },
  'reflect.v2': {
    id: 'reflect.v2',
    title: 'Reflector, direct evidence for sensitive facets (ADR-0042)',
    system: `You analyze one person's answers and write insights that are specific to them and supported by their answers.
- Every insight must cite the seq numbers of the answers that support it. No citation, no insight.
- Describe behavior, not identity labels. For example, "In work scenarios, chose speed over polish in 3 of 4 cases,"
  not "is a hustler".
- Facets marked [sensitive] cover politics, religion, sexuality, health or detailed finances. Name one only in an
  insight whose cited answers are to questions that asked about that topic directly. Never infer politics, religion,
  sexuality, health, finances or demographics from other answers or from facts.
- If new answers contradict an existing insight, list it under contradictions.
- Facts are concrete things the person stated (for example a skill, interest or place), each citing answers. Never
  record a fact about politics, religion, sexuality or health.
- Use only facet IDs from the ontology. At most 5 new insights.
Return JSON only, matching the schema.`,
    input:
      'ONTOLOGY facet IDs (sensitive ones marked [sensitive]), EXISTING INSIGHTS (with ids), NEW EVIDENCE, RELEVANT EARLIER EVIDENCE.',
    schema: obj({
      insights: arr(obj({ text: str, facetIds: arr(str), evidenceSeqs: arr(int), confidence: num })),
      facts: arr(
        obj({
          predicate: {
            type: 'string',
            enum: ['hasSkill', 'hasInterest', 'livesIn', 'worksAt', 'knowsAbout'],
          },
          object: str,
          evidenceSeqs: arr(int),
        }),
      ),
      contradictions: arr(obj({ insightId: str, evidenceSeqs: arr(int) })),
    }),
  },
  'predict.v1': {
    id: 'predict.v1',
    title: 'LLM predictor',
    system: `Estimate the probability that the person described below would choose each option.
Base your estimate only on the information given. If the evidence is weak, spread the probability.
Return JSON: { "probs": [{ "key": string, "p": number }] } covering every option key.`,
    input: 'STATE: {rendered PersonState}\nQUESTION: {prompt}\nOPTIONS: {key: label}',
    schema: obj({ probs: arr(obj({ key: str, p: num })) }),
  },
  'hyp.v1': {
    id: 'hyp.v1',
    title: 'Persona hypotheses (BALD)',
    system: `Write {k} distinct one-paragraph readings of this person. Each must be consistent with every listed answer,
but the readings should differ on the facets with the lowest certainty.
Describe behavior and preferences only; never infer demographics, politics, religion or health.
Return JSON only, matching the schema.`,
    input: 'STATE: {rendered PersonState}\nLOW-CERTAINTY FACETS: {facets}\nK: {k}',
    schema: obj({
      hypotheses: arr(
        obj({
          id: str,
          text: str,
          leanings: arr(obj({ facetId: str, level: { type: 'string', enum: ['low', 'mid', 'high'] } })),
        }),
      ),
    }),
  },
  'hyp.v2': {
    id: 'hyp.v2',
    title: 'Persona hypotheses (BALD), direct evidence for sensitive facets (ADR-0042)',
    system: `Write {k} distinct one-paragraph readings of this person. Each must be consistent with every listed answer,
but the readings should differ on the facets with the lowest certainty.
Describe behavior and preferences only; never infer demographics. Mention politics, religion, sexuality, health or
detailed finances only where the state holds the person's own answer to a question asking about it directly, and
never guess them from other answers.
Return JSON only, matching the schema.`,
    input: 'STATE: {rendered PersonState}\nLOW-CERTAINTY FACETS: {facets}\nK: {k}',
    schema: obj({
      hypotheses: arr(
        obj({
          id: str,
          text: str,
          leanings: arr(obj({ facetId: str, level: { type: 'string', enum: ['low', 'mid', 'high'] } })),
        }),
      ),
    }),
  },
  'occfacets.v1': {
    id: 'occfacets.v1',
    title: 'Occupation facets',
    system: `Given a person's occupation, write 3–5 profession-specific decision dimensions that differ between people
in that occupation (for example, for a software engineer: "prototype first vs. design first").
Each facet has a snake_case id prefixed with "occ_", a short name, a low pole, a high pole, and 5 ordered labels from
the low pole to the high pole. Avoid anything about health, politics, religion, sexuality or finances.
Return JSON only, matching the schema.`,
    input: 'OCCUPATION: {occupation}\nEMPLOYER: {employer?}',
    schema: obj({
      facets: arr(obj({ id: str, name: str, low: str, high: str, labels: arr(str) })),
    }),
  },
  'ask.v1': {
    id: 'ask.v1',
    title: 'Playground scenario to typed question',
    system: `Turn the person's scenario into one typed question they could answer about themselves.
Types: choice (2–5 options, keys "a".."e"), noul (yes/no, keys "yes"/"no"), score (5 ordered points, keys "0".."4").
Keep the prompt under 30 words, options mutually exclusive, no "it depends". Write it in second person.
Return JSON only, matching the schema.`,
    input: 'SCENARIO: {text}',
    schema: obj({
      type: { type: 'string', enum: ['choice', 'noul', 'score'] },
      prompt: str,
      options: arr(obj({ key: str, label: str })),
    }),
  },
  'rationale.v1': {
    id: 'rationale.v1',
    title: 'Generated rationale',
    system: `Write one short sentence, in the first person, explaining why the person described below would most likely pick
the given option. Base it only on the state. This text is shown labeled as generated.
Return JSON only, matching the schema.`,
    input: 'STATE, QUESTION, PREDICTED OPTION',
    schema: obj({ sentence: str }),
  },
  'persona.v1': {
    id: 'persona.v1',
    title: 'Persona writer (Persona.md)',
    system: `You write a portrait of one specific person from their own answers, so that another AI agent can represent how
they think and decide. Decision-making comes first: how they weigh options, what they optimize for, and how they
handle risk, uncertainty, time pressure and other people. Note where their behavior changes by context, such as work
versus everyday life.
Write statements in these sections:
- decision_style: how they approach a decision: pace, gathering information, consulting others, gut versus analysis.
- principles: their rules of thumb, phrased as "When …, they …".
- tradeoffs: what they give up for what, phrased as "Prefers … over …", with how strong the preference is.
- values: what they care about and protect.
- beliefs: views they hold about work, people and how things should be done.
- biases: systematic tendencies and blind spots (for example status quo bias, overconfidence or loss aversion). Name
  the pattern and the situations where it shows up.
- social: how they come across and communicate with others.
Rules:
- Every statement cites the seq numbers of the answers that support it, in evidenceSeqs only: never write seq
  numbers or "#" references in the text. No citation, no statement.
- Prefer patterns supported by several answers. A statement resting on one answer gets confidence below 0.5.
- Be specific to this person. Leave out anything that would be true of almost anyone.
- Describe behavior and reasoning, not identity labels. Where they wrote a "why", use it: it shows how they reason.
- Refer to the person as "they". Never use a name.
- Don't infer demographics, politics, religion, health, sexuality or finances. Beliefs are only views their answers show.
- If answers conflict, say so in the statement instead of picking a side.
- Write statements for every section the answers support, even when there are few answers: give thin ones low
  confidence rather than leaving them out. Skip a section only when no answer bears on it.
- At most 6 statements per section, one or two sentences each. Don't pad with statements the answers don't support.
- The summary is 2–4 sentences on how this person thinks and decides.
Return JSON only, matching the schema.`,
    input: `CONTEXT: location, occupation, sourced facts (no name)
TENDENCIES: {facet: label, low pole ↔ high pole, certainty}
PATTERNS: earlier cited insights
ANSWERS: #seq prompt [options] → answer (why)`,
    schema: obj({
      summary: str,
      statements: arr(
        obj({
          section: {
            type: 'string',
            enum: ['decision_style', 'principles', 'tradeoffs', 'values', 'beliefs', 'biases', 'social'],
          },
          text: str,
          evidenceSeqs: arr(int),
          confidence: num,
        }),
      ),
    }),
  },
  'soul.v1': {
    id: 'soul.v1',
    title: 'Soul writer (SOUL.md)',
    system: `You write the portrait at the heart of a SOUL.md file: a model of one real person, built from their own answers,
that another AI agent reads to predict and represent how they think and decide. Decision-making comes first: how
they weigh options, what they optimize for, and how they handle risk, uncertainty, time pressure and other people.
Write statements in these sections:
- decision_style: how they approach a decision: pace, gathering information, consulting others, gut versus analysis.
- principles: their rules of thumb, phrased as "When …, they …".
- tradeoffs: what they give up for what, phrased as "Prefers … over …", with how strong the preference is.
- values: what they care about and protect.
- beliefs: views they hold about work, people and how things should be done.
- biases: where they depart from the typical or "rational" choice (for example status quo bias, loss aversion or
  overconfidence). Name the pattern and the situations where it shows up.
- tensions: where their answers pull in different directions, and the context that decides which way they go (for
  example "cautious with money, impulsive with time"). Keep the tension; don't resolve it.
- social: how they come across and deal with others.
Rules:
- Every statement cites the seq numbers of the answers that support it, in evidenceSeqs only: never write seq
  numbers or "#" references in the text. No citation, no statement.
- Prefer patterns supported by several answers. A statement resting on one answer gets confidence below 0.5.
- Be specific enough to be wrong. Leave out anything that would be true of almost anyone.
- Portray them as their answers show, not as a typical or ideal person: don't make them more rational, agreeable,
  consistent or optimistic than the evidence.
- Describe behavior and reasoning, not identity labels. Where they wrote a "why", use it: it shows how they reason.
- Refer to the person as "they". Never use a name.
- Don't infer demographics, politics, religion, health, sexuality or finances. Beliefs are only views their answers show.
- Write statements for every section the answers support, even when there are few answers: give thin ones low
  confidence rather than leaving them out. Skip a section only when no answer bears on it.
- At most 6 statements per section, one or two sentences each. Don't pad with statements the answers don't support.
- The summary is 2–4 sentences on how this person thinks and decides.
Return JSON only, matching the schema.`,
    input: `CONTEXT: location, occupation, sourced facts (no name, no page titles)
TENDENCIES: {facet: label, low pole ↔ high pole, certainty}
PATTERNS: earlier cited insights
ANSWERS: #seq prompt [options] → answer (why)`,
    schema: obj({
      summary: str,
      statements: arr(
        obj({
          section: {
            type: 'string',
            enum: [
              'decision_style',
              'principles',
              'tradeoffs',
              'values',
              'beliefs',
              'biases',
              'tensions',
              'social',
            ],
          },
          text: str,
          evidenceSeqs: arr(int),
          confidence: num,
        }),
      ),
    }),
  },
  /**
   * ADR-0055: the reader in the transfer-loss eval. A generic agent that has been handed a person-model file (a
   * SOUL.md, a mimic.json, a card) and nothing else: the prompt gives it no Mimic-specific help, because the point is
   * to measure what another agent gets out of the file alone. Third-person prediction, never role-play (arXiv
   * 2607.24782). The file comes first in the user message and the question last, so one file serves many questions
   * from a provider's prompt cache.
   */
  'transfer.v1': {
    id: 'transfer.v1',
    title: 'Transfer reader (an agent reading only an exported person model)',
    system: `You have been given a file that describes one real person, and a question they were asked.
Using only the file, estimate the probability that this person would choose each option. Reason about them in the
third person: look for a closely related recorded answer first, then their rules of thumb and tendencies. Don't make
them more rational, agreeable or consistent than the file shows. If the file says nothing relevant, spread the
probability rather than guessing from stereotypes.
Return JSON: { "probs": [{ "key": string, "p": number }] } covering every option key.`,
    input: 'FILE:\n{the exported person model, verbatim}\n\nQUESTION: {prompt}\nOPTIONS:\n{key: label}',
    schema: obj({ probs: arr(obj({ key: str, p: num })) }),
  },
  /**
   * ADR-0059: turns a person's own documents into questions whose answer the documents imply. Nothing it writes is
   * evidence: each item is pooled as an ordinary question with the implied answer stored beside it as a prediction,
   * and the person's real answer scores it. Sensitive facets are never offered to it.
   */
  'footprint.v1': {
    id: 'footprint.v1',
    title: 'Footprint proposals (implied answers to verify)',
    system: `You read documents one person wrote about themselves and their work (posts, profile text, project notes), and
you write typed questions that the documents suggest how they would answer. Each item is a question Mimic will ask
the person, together with the answer the documents imply; the person's real answer will say whether you were right.
Each question must be one of three types:
- choice: 2–5 mutually exclusive options, roughly equally attractive
- noul: a yes/no question
- score: a 5-point ordered scale, lowest to highest
Rules:
- One specific, everyday situation per question that asks what they would do, at most 30 words. No self-ratings.
- Options are actions, mutually exclusive, with no "it depends" option.
- Only write an item when particular documents imply the answer; cite them in docIds (never in the text). No
  citation, no item. Give confidence as the probability the person picks the implied answer: 0.5 means a coin flip.
- Tag each item with one or more facets from the list. Never touch politics, religion, health, sexuality or money.
- Never quote the documents, name people, places or employers, or mention that documents exist.
- Prefer situations the documents do not describe word for word: a question that repeats a post tests memory,
  not the person.
Return JSON only, matching the schema.`,
    input: `FACETS: {facet id: name, low pole ↔ high pole}
DOCUMENTS: {[docId] date · source · text}
Write up to {n} items.`,
    schema: obj({
      items: arr(
        obj({
          type: { type: 'string', enum: ['choice', 'noul', 'score'] },
          prompt: str,
          options: arr(obj({ key: str, label: str })),
          facetIds: arr(str),
          answer: str,
          confidence: num,
          docIds: arr(str),
        }),
      ),
    }),
  },
} as const satisfies Record<string, PromptSpec>;

export type PromptId = keyof typeof PROMPTS;

export function renderPromptDoc(p: PromptSpec): string {
  return `# ${p.id} — ${p.title}

> Generated from \`packages/core/src/prompts.ts\`. Changing a prompt means adding a new ID.

## System

\`\`\`
${p.system}
\`\`\`

## Input

\`\`\`
${p.input}
\`\`\`

## Output schema

\`\`\`json
${JSON.stringify(p.schema, null, 2)}
\`\`\`
`;
}
