import type { ReactNode } from 'react';

/** Inline `code` spans; everything else is text (React escapes it). */
function inline(text: string): ReactNode[] {
  return text.split(/(`[^`]+`)/g).map((part, i) =>
    part.startsWith('`') && part.endsWith('`') && part.length > 1 ? (
      // biome-ignore lint/suspicious/noArrayIndexKey: static split of a string
      <code key={i} className="rounded bg-surface px-1 font-mono text-[12px]">
        {part.slice(1, -1)}
      </code>
    ) : (
      part
    ),
  );
}

const cells = (row: string) =>
  row
    .trim()
    .replace(/^\||\|$/g, '')
    .split('|')
    .map((c) => c.trim());

/**
 * Renders the markdown subset `mimic-eval report` writes (headings, bullets, tables, paragraphs, inline code).
 * Reports are generated by our CLI, not user input; no HTML is interpreted.
 */
export function ReportView({ markdown }: { markdown: string }) {
  const lines = markdown.split('\n');
  const out: ReactNode[] = [];
  for (let i = 0; i < lines.length; i++) {
    const line = lines[i]!;
    if (!line.trim()) continue;
    if (line.startsWith('# ')) continue; // the page title shows the run name
    if (line.startsWith('## ')) {
      out.push(
        <h2 key={i} className="mt-8 mb-3 font-serif text-xl tracking-tight">
          {inline(line.slice(3))}
        </h2>,
      );
    } else if (line.startsWith('- ')) {
      const items: string[] = [];
      while (i < lines.length && lines[i]!.startsWith('- ')) items.push(lines[i++]!.slice(2));
      i--;
      out.push(
        <ul key={i} className="list-disc space-y-1 pl-5 text-[13px] text-graphite">
          {items.map((it, j) => (
            // biome-ignore lint/suspicious/noArrayIndexKey: static list
            <li key={j}>{inline(it)}</li>
          ))}
        </ul>,
      );
    } else if (line.startsWith('|')) {
      const rows: string[][] = [];
      while (i < lines.length && lines[i]!.startsWith('|')) {
        if (!/^\|[\s|:-]+\|$/.test(lines[i]!.trim())) rows.push(cells(lines[i]!));
        i++;
      }
      i--;
      const [head, ...body] = rows;
      out.push(
        <div key={i} className="overflow-x-auto rounded-[var(--radius-card)] border border-line bg-raised">
          <table className="w-full text-[12.5px] tabular-nums">
            <thead className="bg-surface text-left text-muted">
              <tr>
                {head?.map((h, j) => (
                  // biome-ignore lint/suspicious/noArrayIndexKey: static header
                  <th key={j} className="px-3 py-2 font-medium whitespace-nowrap">
                    {inline(h)}
                  </th>
                ))}
              </tr>
            </thead>
            <tbody>
              {body.map((r, j) => (
                // biome-ignore lint/suspicious/noArrayIndexKey: static rows
                <tr key={j} className="border-t border-line">
                  {r.map((c, k) => (
                    // biome-ignore lint/suspicious/noArrayIndexKey: static cells
                    <td key={k} className="px-3 py-2 whitespace-nowrap">
                      {inline(c)}
                    </td>
                  ))}
                </tr>
              ))}
            </tbody>
          </table>
        </div>,
      );
    } else {
      out.push(
        <p key={i} className="my-3 text-[13px] text-graphite">
          {inline(line)}
        </p>,
      );
    }
  }
  return <div>{out}</div>;
}
