import type { Category, Facet, SensitiveArea } from '../types';
import { ONTOLOGY_V1 } from './v1';

type L5 = [string, string, string, string, string];

/**
 * Ontology v2 (ADR-0042). Every v1 facet keeps its id, poles and labels, so readings stay comparable across
 * versions; only its group changes. Each group sits in exactly one category (ADR-0040). New facets fill the gaps
 * named in PLAN §14 M10: emotion and motivation, moral foundations, beliefs about people and the world, attachment,
 * money psychology and the five sensitive areas, each behind its own consent. Every facet carries the research anchor
 * it was modelled on (`source`), rendered into `docs/ontology/v2.sources.md`.
 */
export const FACET_GROUPS_V2 = [
  'Personality',
  'Decisions',
  'Emotion and motivation',
  'Values and morality',
  'Beliefs and worldview',
  'Social and communication',
  'Relationships and intimacy',
  'Everyday and health',
  'Work',
  'Money',
] as const;
export type FacetGroupV2 = (typeof FACET_GROUPS_V2)[number];

export const GROUP_CATEGORY_V2: Record<FacetGroupV2, Category> = {
  Personality: 'psychology',
  Decisions: 'psychology',
  'Emotion and motivation': 'psychology',
  'Values and morality': 'values',
  'Beliefs and worldview': 'values',
  'Social and communication': 'life',
  'Relationships and intimacy': 'life',
  'Everyday and health': 'life',
  Work: 'work',
  Money: 'work',
};

const V1_GROUP: Record<string, FacetGroupV2> = {
  Personality: 'Personality',
  Decisions: 'Decisions',
  Values: 'Values and morality',
  Social: 'Social and communication',
  Communication: 'Social and communication',
  Everyday: 'Everyday and health',
  Work: 'Work',
};
const V1_GROUP_OVERRIDE: Record<string, FacetGroupV2> = { spending_style: 'Money' };

const BIG_FIVE = 'Goldberg 1992, Big-Five factor markers; IPIP public-domain items (ipip.ori.org)';
const SCHWARTZ = 'Schwartz 1992, theory of basic human values; Schwartz et al. 2012, refined theory';
const COMM_STYLE = 'Norton 1978, Communicator Style Measure';

/** Research anchors for the v1 facets, which v1 itself never recorded. */
const V1_SOURCES: Record<string, string> = {
  openness: BIG_FIVE,
  conscientiousness: BIG_FIVE,
  extraversion: BIG_FIVE,
  agreeableness: BIG_FIVE,
  emotional_stability: BIG_FIVE,
  openness_to_change: SCHWARTZ,
  self_enhancement: SCHWARTZ,
  conservation: SCHWARTZ,
  self_transcendence: SCHWARTZ,
  risk_tolerance: 'Dohmen et al. 2011, general risk question; Falk et al. 2018, Global Preference Survey',
  patience: "Frederick, Loewenstein & O'Donoghue 2002, time preference; Falk et al. 2018",
  loss_aversion: 'Kahneman & Tversky 1979, prospect theory; Gächter, Johnson & Herrmann 2022',
  ambiguity_tolerance: 'Ellsberg 1961; Budner 1962, intolerance of ambiguity',
  maximizing: 'Schwartz et al. 2002, Maximization Scale',
  deliberation:
    'Epstein et al. 1996, Rational-Experiential Inventory; Frederick 2005, Cognitive Reflection Test',
  trust: 'Berg, Dickhaut & McCabe 1995, trust game; Falk et al. 2018',
  reciprocity: 'Fehr & Gächter 2000, fairness and retaliation; Falk et al. 2018',
  conformity: 'Asch 1956; Cialdini & Goldstein 2004, social influence',
  conflict_directness: 'Thomas & Kilmann 1974, conflict mode instrument',
  autonomy: 'Hackman & Oldham 1976, job characteristics model',
  planning: 'Lynch et al. 2010, propensity to plan',
  detail_orientation: 'Costa & McCrae 1992, NEO-PI-R order facet',
  collaboration: 'Wagner 1995, individualism and collectivism in groups',
  leadership_drive: 'Chan & Drasgow 2001, motivation to lead',
  speed_vs_quality: 'Förster, Higgins & Bianco 2003, speed and accuracy in task performance',
  routine: 'Ersche et al. 2017, Creature of Habit Scale',
  social_energy: 'Eysenck 1967; IPIP gregariousness',
  spending_style: 'Rick, Cryder & Loewenstein 2008, Tightwad-Spendthrift Scale',
  taste_novelty: 'Steenkamp & Baumgartner 1992, exploratory buying; Pliner & Hobden 1992, food neophobia',
  directness: COMM_STYLE,
  formality: COMM_STYLE,
  verbosity: COMM_STYLE,
  humor: `${COMM_STYLE}; Martin et al. 2003, Humor Styles Questionnaire`,
};

const FROM_V1: Facet[] = ONTOLOGY_V1.map((f) => ({
  ...f,
  group: V1_GROUP_OVERRIDE[f.id] ?? V1_GROUP[f.group]!,
  source: V1_SOURCES[f.id]!,
}));

const n = (
  id: string,
  group: FacetGroupV2,
  name: string,
  low: string,
  high: string,
  labels: L5,
  source: string,
  sensitive?: SensitiveArea,
): Facet => ({
  id,
  group,
  name,
  low,
  high,
  labels,
  category: GROUP_CATEGORY_V2[group],
  source,
  ...(sensitive ? { sensitive } : {}),
});

const MFQ = 'Graham et al. 2011, Moral Foundations Questionnaire; Atari et al. 2023, MFQ-2';

/** Facets new in v2, in group order. */
export const NEW_IN_V2: Facet[] = [
  // Emotion and motivation (psychology)
  n(
    'emotion_regulation',
    'Emotion and motivation',
    'emotion regulation',
    'Holds feelings in or dwells on them',
    'Reframes and moves on',
    [
      'Usually holds feelings in or dwells on them',
      'Leans toward holding in or dwelling',
      'Balanced',
      'Leans toward reframing',
      'Usually reframes and moves on',
    ],
    'Gross & John 2003, Emotion Regulation Questionnaire (reappraisal vs. suppression)',
  ),
  n(
    'emotional_expressiveness',
    'Emotion and motivation',
    'emotional expressiveness',
    'Keeps feelings private',
    'Shows feelings openly',
    ['Keeps feelings very private', 'Leans private', 'Balanced', 'Leans open', 'Shows feelings very openly'],
    'Gross & John 1997, Berkeley Expressivity Questionnaire',
  ),
  n(
    'punishment_sensitivity',
    'Emotion and motivation',
    'sensitivity to setbacks',
    'Shrugs off what could go wrong',
    'Alert to what could go wrong',
    [
      'Shrugs off setbacks and threats',
      'Leans unbothered',
      'Balanced',
      'Leans alert to setbacks',
      'Very alert to what could go wrong',
    ],
    'Carver & White 1994, BIS/BAS scales (behavioural inhibition)',
  ),
  n(
    'reward_sensitivity',
    'Emotion and motivation',
    'reward drive',
    'Unmoved by rewards and thrills',
    'Driven by rewards and thrills',
    [
      'Rarely moved by rewards or thrills',
      'Leans unmoved',
      'Balanced',
      'Leans reward-driven',
      'Strongly driven by rewards and thrills',
    ],
    'Carver & White 1994, BIS/BAS scales (reward responsiveness, drive, fun seeking)',
  ),
  n(
    'need_for_cognition',
    'Emotion and motivation',
    'need for cognition',
    'Avoids effortful thinking',
    'Enjoys hard problems',
    [
      'Avoids effortful thinking',
      'Leans toward easy options',
      'Balanced',
      'Leans toward hard problems',
      'Seeks out hard problems',
    ],
    'Cacioppo & Petty 1982, Need for Cognition Scale',
  ),
  n(
    'growth_mindset',
    'Emotion and motivation',
    'growth mindset',
    'Abilities are fixed',
    'Abilities can grow',
    [
      'Sees abilities as fixed',
      'Leans fixed',
      'Balanced',
      'Leans toward growth',
      'Sees abilities as able to grow',
    ],
    'Dweck 1999, Self-theories; Dweck, Chiu & Hong 1995, implicit theories',
  ),
  n(
    'self_control',
    'Emotion and motivation',
    'self-control',
    'Gives in to impulses',
    'Resists temptation',
    [
      'Usually gives in to impulses',
      'Leans toward giving in',
      'Balanced',
      'Leans toward resisting',
      'Reliably resists temptation',
    ],
    'Tangney, Baumeister & Boone 2004, Brief Self-Control Scale',
  ),
  // Values and morality (values)
  n(
    'care_harm',
    'Values and morality',
    'care',
    'Harm is a cost to weigh',
    'Preventing harm comes first',
    [
      'Treats harm as one cost among others',
      'Leans pragmatic about harm',
      'Balanced',
      'Leans toward preventing harm',
      'Puts preventing harm first',
    ],
    `${MFQ} (care)`,
  ),
  n(
    'fairness_cheating',
    'Values and morality',
    'fairness',
    'Winning matters more than fair play',
    'Fair play comes first',
    [
      'Winning matters more than fair play',
      'Leans toward winning',
      'Balanced',
      'Leans toward fair play',
      'Fair play comes first',
    ],
    `${MFQ} (fairness, proportionality)`,
  ),
  n(
    'loyalty_betrayal',
    'Values and morality',
    'loyalty',
    'Loyal to principles, not people or groups',
    'Stands by their people',
    [
      'Loyal to principles over people',
      'Leans toward principles',
      'Balanced',
      'Leans toward their people',
      'Stands by their people',
    ],
    `${MFQ} (loyalty)`,
  ),
  n(
    'authority_subversion',
    'Values and morality',
    'respect for authority',
    'Questions authority and tradition',
    'Respects authority and tradition',
    [
      'Readily questions authority and tradition',
      'Leans questioning',
      'Balanced',
      'Leans respectful',
      'Strongly respects authority and tradition',
    ],
    `${MFQ} (authority)`,
  ),
  n(
    'liberty_oppression',
    'Values and morality',
    'liberty',
    'Accepts limits for the common good',
    'Resists limits on freedom',
    [
      'Readily accepts limits for the common good',
      'Leans toward accepting limits',
      'Balanced',
      'Leans toward resisting limits',
      'Strongly resists limits on freedom',
    ],
    'Iyer et al. 2012, liberty foundation',
  ),
  n(
    'honesty_humility',
    'Values and morality',
    'honesty',
    'Shades the truth for an advantage',
    'Honest even at a cost',
    [
      'Shades the truth for an advantage',
      'Leans toward advantage',
      'Balanced',
      'Leans toward honesty',
      'Honest even at a cost',
    ],
    'Ashton & Lee 2007, HEXACO honesty-humility; Fischbacher & Föllmi-Heusi 2013, lying in private',
  ),
  n(
    'norm_compliance',
    'Values and morality',
    'rule following',
    'Bends rules when unobserved',
    'Follows rules even when unobserved',
    [
      'Readily bends rules when unobserved',
      'Leans toward bending',
      'Balanced',
      'Leans toward following',
      'Follows rules even when unobserved',
    ],
    'Kimbrough & Vostroknutov 2016, rule-following task',
  ),
  // Beliefs and worldview (values)
  n(
    'locus_of_control',
    'Beliefs and worldview',
    'locus of control',
    'Outcomes come from luck and others',
    'Outcomes come from own actions',
    [
      'Credits luck and others for outcomes',
      'Leans toward luck and others',
      'Balanced',
      'Leans toward own actions',
      'Credits own actions for outcomes',
    ],
    'Rotter 1966, internal-external control; Levenson 1981',
  ),
  n(
    'optimism',
    'Beliefs and worldview',
    'optimism',
    'Expects the worst',
    'Expects the best',
    ['Expects the worst', 'Leans pessimistic', 'Balanced', 'Leans optimistic', 'Expects the best'],
    'Scheier, Carver & Bridges 1994, Life Orientation Test-Revised',
  ),
  n(
    'just_world',
    'Beliefs and worldview',
    'belief in a just world',
    'The world is often unfair',
    'People get what they deserve',
    [
      'Sees the world as often unfair',
      'Leans toward unfair',
      'Balanced',
      'Leans toward just',
      'Believes people get what they deserve',
    ],
    'Lipkus 1991, Global Belief in a Just World Scale; Dalbert 1999',
  ),
  n(
    'political_leaning',
    'Beliefs and worldview',
    'political leaning',
    'Left or progressive',
    'Right or conservative',
    ['Clearly left or progressive', 'Centre-left', 'Centre', 'Centre-right', 'Clearly right or conservative'],
    'European Social Survey left-right self-placement; Jost 2006',
    'politics',
  ),
  n(
    'political_engagement',
    'Beliefs and worldview',
    'political engagement',
    'Stays out of politics',
    'Actively involved in politics',
    [
      'Stays out of politics',
      'Votes, little more',
      'Follows and votes',
      'Discusses and campaigns now and then',
      'Actively involved',
    ],
    'Verba, Schlozman & Brady 1995, civic participation; ANES participation items',
    'politics',
  ),
  n(
    'religiosity',
    'Beliefs and worldview',
    'religiosity',
    'Not religious',
    'Deeply religious',
    ['Not religious', 'Slightly religious', 'Moderately religious', 'Quite religious', 'Deeply religious'],
    'Koenig & Büssing 2010, Duke University Religion Index (DUREL)',
    'religion',
  ),
  n(
    'spirituality',
    'Beliefs and worldview',
    'spirituality',
    'Secular, natural explanations',
    'Sense of something greater',
    [
      'Firmly secular',
      'Leans secular',
      'Open or unsure',
      'Leans spiritual',
      'Strong sense of something greater',
    ],
    'Piedmont 1999, Spiritual Transcendence Scale; Underwood & Teresi 2002',
    'religion',
  ),
  // Relationships and intimacy (life)
  n(
    'attachment_anxiety',
    'Relationships and intimacy',
    'attachment anxiety',
    'Secure about closeness',
    'Worries about being let down or left',
    ['Secure about closeness', 'Leans secure', 'Balanced', 'Leans worried', 'Often worries about being left'],
    'Wei et al. 2007, ECR-S (anxiety); Fraley, Waller & Brennan 2000',
  ),
  n(
    'attachment_avoidance',
    'Relationships and intimacy',
    'attachment avoidance',
    'Comfortable depending on others',
    'Keeps others at a distance',
    [
      'Comfortable depending on others',
      'Leans toward closeness',
      'Balanced',
      'Leans toward distance',
      'Keeps others at a distance',
    ],
    'Wei et al. 2007, ECR-S (avoidance); Fraley, Waller & Brennan 2000',
  ),
  n(
    'social_comparison',
    'Relationships and intimacy',
    'social comparison',
    'Rarely compares with others',
    'Often compares with others',
    [
      'Rarely compares with others',
      'Leans away from comparing',
      'Balanced',
      'Leans toward comparing',
      'Often compares with others',
    ],
    'Gibbons & Buunk 1999, Iowa-Netherlands Comparison Orientation Measure',
  ),
  n(
    'forgiveness',
    'Relationships and intimacy',
    'forgiveness',
    'Holds grudges',
    'Forgives readily',
    ['Holds grudges', 'Leans toward grudges', 'Balanced', 'Leans forgiving', 'Forgives readily'],
    'McCullough et al. 1998, TRIM inventory',
  ),
  n(
    'sociosexuality',
    'Relationships and intimacy',
    'sociosexuality',
    'Sex only with commitment',
    'Comfortable with casual sex',
    [
      'Only within a committed relationship',
      'Mostly with commitment',
      'Balanced',
      'Leans open to casual',
      'Comfortable with casual sex',
    ],
    'Penke & Asendorpf 2008, Revised Sociosexual Orientation Inventory',
    'sexuality',
  ),
  n(
    'relationship_exclusivity',
    'Relationships and intimacy',
    'relationship exclusivity',
    'Wants an exclusive relationship',
    'Open to non-exclusive relationships',
    [
      'Wants an exclusive relationship',
      'Leans exclusive',
      'Open either way',
      'Leans open to non-exclusive',
      'Prefers non-exclusive',
    ],
    'Conley et al. 2013, attitudes toward consensual non-monogamy',
    'sexuality',
  ),
  // Everyday and health (life)
  n(
    'health_vigilance',
    'Everyday and health',
    'health vigilance',
    'Relaxed about health',
    'Closely tracks health',
    ['Very relaxed about health', 'Leans relaxed', 'Balanced', 'Leans watchful', 'Closely tracks health'],
    'Wallston, Wallston & DeVellis 1978, Multidimensional Health Locus of Control; Gould 1988, health consciousness',
    'health',
  ),
  n(
    'body_image',
    'Everyday and health',
    'body image',
    'Critical of own body',
    'Appreciates own body',
    ['Mostly critical of own body', 'Leans critical', 'Mixed', 'Leans appreciative', 'Appreciates own body'],
    'Tylka & Wood-Barcalow 2015, Body Appreciation Scale-2',
    'health',
  ),
  n(
    'substance_use',
    'Everyday and health',
    'alcohol and substances',
    'Abstains or rarely uses',
    'Uses often',
    ['Abstains', 'Rarely', 'Now and then, in moderation', 'Regularly', 'Often and freely'],
    'Bush et al. 1998, AUDIT-C',
    'health',
  ),
  // Money (work)
  n(
    'mental_accounting',
    'Money',
    'mental accounting',
    'All money is the same money',
    'Keeps money in separate pots',
    [
      'Treats all money the same',
      'Leans toward one pot',
      'Balanced',
      'Leans toward separate pots',
      'Keeps money in separate pots',
    ],
    'Thaler 1999, mental accounting; Heath & Soll 1996, mental budgeting',
  ),
  n(
    'materialism',
    'Money',
    'materialism',
    'Experiences over possessions',
    'Possessions matter',
    [
      'Strongly prefers experiences',
      'Leans toward experiences',
      'Balanced',
      'Leans toward possessions',
      'Possessions matter a lot',
    ],
    'Richins & Dawson 1992, Material Values Scale; Van Boven & Gilovich 2003',
  ),
  n(
    'financial_security',
    'Money',
    'financial security',
    'Money is a constant worry',
    'Financially secure',
    [
      'Money is a constant worry',
      'Often stretched',
      'Getting by',
      'Mostly comfortable',
      'Financially secure',
    ],
    'CFPB 2015, Financial Well-Being Scale; Netemeyer et al. 2018',
    'money',
  ),
  n(
    'debt_attitude',
    'Money',
    'attitude to debt',
    'Avoids debt',
    'Comfortable borrowing',
    [
      'Avoids debt at almost any cost',
      'Leans against borrowing',
      'Balanced',
      'Leans comfortable borrowing',
      'Comfortable borrowing',
    ],
    'Lea, Webley & Walker 1995, psychology of consumer debt; Almenberg et al. 2021',
    'money',
  ),
];

/** Ontology v2: v1 facets regrouped, then the new ones, sorted by group so views read in order. */
export const ONTOLOGY_V2: Facet[] = FACET_GROUPS_V2.flatMap((g) =>
  [...FROM_V1, ...NEW_IN_V2].filter((f) => f.group === g),
);
